# myhelmappwordpress-values.yaml
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /wordpress
  hosts:
    - host: myhelmapp.example.com
      paths:
        - /wordpress
  tls:
    - secretName: myhelmappwordpress-tls
      hosts:
        - myhelmapp.example.com
