# myhelmapp-values.yaml
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: myhelmapp.example.com
      paths:
        - /
  tls:
    - secretName: myhelmapp-tls
      hosts:
        - myhelmapp.example.com
