kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.configmap.name }}
data:
  BG_COLOR: '#12181b'
  FONT_COLOR: '#FFFFFF'
  CUSTOM_HEADER: {{ .Values.configmap.data.CUSTOM_HEADER }}
  MYSQL_ROOT_PASSWORD: 'password'
  MYSQL_DATABASE: 'database'
  MYSQL_USER: 'user'
  MYSQL_PASSWORD: 'password'