apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}database
  labels:
    app: {{ .Values.appName }}database
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}database
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}database
        tier: frontend
    spec: # Pod spec
      containers:
      - name: database-container
        image: "{{ .Values.image_database.name }}:{{ .Values.image_database.tag }}"
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"