# File: myhelmapp/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myhelmapp-ingress
  namespace: youtube
spec:
  rules:
  - host: myhelmapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myhelmapp
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myhelmappwordpress-ingress
spec:
  rules:
  - host: myhelmapp.example.com
    http:
      paths:
      - path: /wordpress
        pathType: Prefix
        backend:
          service:
            name: myhelmappwordpress
            port:
              number: 80
