apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}wordpress
  labels:
    app: {{ .Values.appName }}wordpress
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  selector:
    app: {{ .Values.appName }}wordpress
    tier: frontend
  type: ClusterIP
